raw_data:
    n_files:
        HH: [ 0, 259 ]
        LH: [ 0, 259 ]
        cont: [ 1, 259 ]

    folder: extra/data/ta_analysis/
    sample_label: BS066

    ta_data:
        HH: "%s_HHEx_1.0mW_%d.txt"
        LH: "%s_LHEx_1.1mW_%d.txt"
        cont: "%s_cont.Ex_1.1mW_%d.txt"

    time_data:
        HH: "times_%s_HHEx_1.0mW.txt"
        LH: "times_%s_LHEx_1.1mW.txt"
        cont: "times_%s_cont.Ex_1.1mW.txt"

    pump_sigma:
        HH: 0.014089824005878092
        LH: 0.014089824005878092
        cont: 0.014089824005878092

    pump_mu:
        HH: 2.4188 # eV
        LH: 2.5833 # eV
        cont: 3.1 # eV

    tau_pump: 0.05 # ps
    pump_shift: 0.1 # ps

    ta_times_start:
        HH:  10 # 27
        LH: 10 # 22
        cont: 10 # 25

    ta_times_zero:
        HH: 41
        LH: 37
        cont: 48

    n_smooth_passes: 20
    n_avg_items: 2

abs_data:
    folder: extra/extcharge/export_abs/
    file: "%s_vo_sum.csv"

settings:
    N_E: 256
    plot_cases: [ HH, LH, cont ]

fit_vars_model_biexc:
    fse:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    fdepl:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.008 ]

    fdepl2:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.0015 ]
    
    abs_shift:
        unit: 'eV'
        p0: 0.0125
        bounds: [ 0.006, 0.015 ]

    hhhh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.41
        bounds: [ 2.39, 2.43 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.03
        bounds: [ 0.02, 0.04 ]

    hhlh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.007 ]

    hhlh_loc:
        unit: 'eV'
        p0: 2.5
        bounds: [ 2.495, 2.52 ]

    hhlh_sig:
        unit: 'eV'
        p0: 0.02
        bounds: [ 0.02, 0.035 ]

fit_vars_model_biexc_v2:
    fse:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    fdepl:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.008 ]

    abs_shift:
        unit: 'eV'
        p0: 0.0125
        bounds: [ 0.006, 0.015 ]

    hhhh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.41
        bounds: [ 2.39, 2.43 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.03
        bounds: [ 0.02, 0.04 ]

    lh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.007 ]

fit_chem_eq_pump:
    n_gamma_0:
        unit: ''
        p0: 0.05
        bounds: [ 0.001, 0.15 ]

    r_q:
        unit: ''
        p0: 0.01
        bounds: [ 0.0001, 0.2 ]

    tau_mu:
        unit: 'ps'
        p0: 0.6
        bounds: [ 0.4, 1.0 ]

    sigma_q:
        unit: ''
        p0: 5.0
        bounds: [ 3.0, 8.0 ]

    tau_qt:
        unit: 'ps'
        p0: 0.005
        bounds: [ 0.0005, 0.3 ]

    tau_Xt:
        unit: 'ps'
        p0: 0.05
        bounds: [ 0.04, 0.08 ]

    tau_pump:
        unit: 'ps'
        p0: 0.06
        bounds: [ 0.03, 0.1 ]

    pump_shift:
        unit: 'ps'
        p0: 1.0
        bounds: [ 0.5, 1.5 ]

    chi_t_total:
        unit: ''
        p0:
            HH: 0.7
            LH: 0.3
            cont: 0.4
        bounds: [ 0.05, 0.8 ]

    tau_decay:
        unit: 'ps'
        p0: 80.0
        bounds: [ 50.0, 150.0 ]

