raw_data:
    n_files:
        HH: [ 0, 259 ]
        LH: [ 0, 259 ]
        cont: [ 1, 259 ]

    folder: extra/data/ta_analysis/
    sample_label: BS066

    ta_data:
        HH: "%s_HHEx_1.0mW_%d.txt"
        LH: "%s_LHEx_1.4mW_%d.txt"
        cont: "%s_cont.Ex_1.5mW_%d.txt"

    time_data:
        HH: "times_%s_HHEx_1.0mW.txt"
        LH: "times_%s_LHEx_1.4mW.txt"
        cont: "times_%s_cont.Ex_1.5mW.txt"

    pump_sigma:
        HH: 0.014089824005878092
        LH: 0.014089824005878092
        cont: 0.014089824005878092

    pump_mu:
        HH: 2.4188 # eV
        LH: 2.5833 # eV
        cont: 3.1 # eV

    ta_times_start:
        HH: 30 # 27
        LH: 26 # 22
        cont: 30 # 25

    ta_times_zero:
        HH: 41
        LH: 37
        cont: 48

    n_smooth_passes: 20
    n_avg_items: 2

abs_data:
    folder: extra/extcharge/export_abs/
    file: "%s_vo_sum.csv"

settings:
    N_E: 256
    plot_cases: [ HH, LH, cont ]

fit_vars_model_biexc:
    fse:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    fdepl:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.012 ]

    fdepl2:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.004 ]
    
    abs_shift:
        unit: 'eV'
        p0: 0.0125
        bounds: [ 0.006, 0.015 ]

    hhhh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.41
        bounds: [ 2.39, 2.43 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.03
        bounds: [ 0.02, 0.04 ]

    hhlh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.007 ]

    hhlh_loc:
        unit: 'eV'
        p0: 2.5
        bounds: [ 2.495, 2.52 ]

    hhlh_sig:
        unit: 'eV'
        p0: 0.02
        bounds: [ 0.02, 0.035 ]

fit_chem_eq:
    n_q_0:
        unit: ''
        p0: 0.0005
        bounds: [ 0.0, 1.0e-1 ]

    n_X_0:
        unit: ''
        p0: 0.04
        bounds: [ 0.0, 3.0 ]

    n_t_0:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.7 ]

    chi_t_total:
        unit: ''
        p0: 0.5
        bounds: [ 0.0, 1.0 ]

    tau_mu:
        unit: 'ps'
        p0: 0.3
        bounds: [ 0.1, 0.7 ]

    tau_qt:
        unit: 'ps'
        p0: 0.01
        bounds: [ 0.001, 0.05 ]

    tau_Xt:
        unit: 'ps'
        p0: 0.12
        bounds: [ 0.08, 0.3 ]

    tau_decay:
        unit: 'ps'
        p0: 100.0
        bounds: [ 5.0, 500.0 ]

    sigma_q:
        unit: ''
        p0: 5.0
        bounds: [ 0.0, 10.0 ]

fit_chem_eq_pump:
    n_gamma_0:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 0.5 ]

    r_q:
        unit: ''
        p0: 0.5
        bounds: [ 0.0, 1.0 ]

    tau_pump:
        unit: 'ps'
        p0: 0.05
        bounds: [ 0.001, 0.1 ]

    tau_mu:
        unit: 'ps'
        p0: 0.6
        bounds: [ 0.1, 0.7 ]

    sigma_q:
        unit: ''
        p0: 5.0
        bounds: [ 0.0, 10.0 ]

    tau_qt:
        unit: 'ps'
        p0: 0.01
        bounds: [ 0.0001, 0.05 ]

    tau_Xt:
        unit: 'ps'
        p0: 0.05
        bounds: [ 0.03, 0.3 ]

    chi_t_total:
        unit: ''
        p0: 0.5
        bounds: [ 0.0, 1.0 ]
