raw_data:
    n_files:
        HH: [ 0, 259 ]
        LH: [ 0, 259 ]
        cont: [ 1, 259 ]

    folder: extra/data/ta_analysis/
    sample_label: BS066

    ta_data:
        HH: "%s_HHEx_1.0mW_%d.txt"
        LH: "%s_LHEx_1.4mW_%d.txt"
        cont: "%s_cont.Ex_1.5mW_%d.txt"

    time_data:
        HH: "times_%s_HHEx_1.0mW.txt"
        LH: "times_%s_LHEx_1.4mW.txt"
        cont: "times_%s_cont.Ex_1.5mW.txt"

    pump_sigma:
        HH: 0.014089824005878092
        LH: 0.014089824005878092
        cont: 0.014089824005878092

    pump_mu:
        HH: 2.4188 # eV
        LH: 2.5833 # eV
        cont: 3.1 # eV

    ta_times_zero:
        HH: 41
        LH: 37
        cont: 48

    n_smooth_passes: 20
    n_avg_items: 2

abs_data:
    folder: extra/extcharge/export_abs/
    file: "%s_vo_sum.csv"

settings:
    N_E: 256
    plot_cases: [ HH, LH, cont ]

fit_vars_model_biexc:
    fse:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    abs_shift:
        unit: 'eV'
        p0: 0.0
        bounds: [ -0.005, 0.015 ]

    alpha:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 1.0 ]

    fdepl:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.01 ]

    fdepl2:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.004 ]

    hhhh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.05 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.41
        bounds: [ 2.39, 2.43 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.03
        bounds: [ 0.02, 0.04 ]

    hhlh_mag:
        unit: ''
        p0: 0.0
        bounds: [ 0.0, 0.007 ]

    hhlh_loc:
        unit: 'eV'
        p0: 2.5
        bounds: [ 2.495, 2.52 ]

    hhlh_sig:
        unit: 'eV'
        p0: 0.02
        bounds: [ 0.02, 0.035 ]

fit_chem_eq:
    n_q_0:
        unit: ''
        p0:
            HH: 0.1
            LH: 0.9
            cont: 1.0
        bounds: [ 0.0, 1.0 ]

    n_X_0:
        unit: ''
        p0:
            HH: 1.9
            LH: 1.1
            cont: 1.0
        bounds: [ 0.0, 1.0 ]

    chi_t_total:
        unit: ''
        p0: 0.5
        bounds: [ 0.0, 1.0 ]

    tau_mu:
        unit: 'ps'
        p0: 0.7
        bounds: [ 0.05, 0.5 ]

    tau_qt:
        unit: 'ps'
        p0: 0.01
        bounds: [ 0.0, 10.0 ]

    tau_Xt:
        unit: 'ps'
        p0: 0.12
        bounds: [ 0.0, 0.2 ]
