raw_data:
    n_files:
        HH: [ 0, 259 ]
        LH: [ 0, 259 ]
        cont: [ 1, 259 ]

    folder: extra/data/ta_analysis/
    sample_label: BS066

    ta_data:
        HH: "%s_HHEx_1.0mW_%d.txt"
        LH: "%s_LHEx_1.4mW_%d.txt"
        cont: "%s_cont.Ex_1.5mW_%d.txt"

    time_data:
        HH: "times_%s_HHEx_1.0mW.txt"
        LH: "times_%s_LHEx_1.4mW.txt"
        cont: "times_%s_cont.Ex_1.5mW.txt"

    pump_sigma:
        HH: 0.014089824005878092
        LH: 0.014089824005878092
        cont: 0.014089824005878092

abs_data:
    folder: extra/extcharge/export_abs/
    file: "%s_vo_sum.csv"

settings:
    N_E: 256
    plot_cases: [ HH, LH, cont ]

fit_vars:
    fse:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]

    fdepl:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]

    alpha:
        unit: ''
        p0: 0.01
        bounds: [ 0.0, 1.0 ]

    pump_mu:
        unit: 'eV'
        p0:
            HH: 2.4188
            LH: 2.5833
            cont: 3.1
        bounds:
            HH: [ 2.4, 2.45 ]
            LH: [ 2.58, 2.7 ]
            cont: [ 3.05, 3.3 ]

    hhhh_mag:
        unit: ''
        p0: 0.005
        bounds: [ 0.0, 1.0 ]

    hhlh_mag:
        unit: ''
        p0: 0.005
        bounds: [ 0.0, 1.0 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.38
        bounds: [ 2.3, 2.4 ]

    hhlh_loc:
        unit: 'eV'
        p0: 2.5
        bounds: [ 2.45, 2.55 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.02
        bounds: [ 0.01, 0.03 ]

    hhlh_sig:
        unit: 'eV'
        p0: 0.02
        bounds: [ 0.01, 0.03 ]

fit_vars_model:
    fse:
        unit: ''
        p0: 0.01
        bounds: [ 0.0, 1.0 ]

    fdepl:
        unit: ''
        p0: 0.01
        bounds: [ 0.0, 1.0 ]

    alpha:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]

    pump_mu:
        unit: 'eV'
        p0:
            HH: 2.4188
            LH: 2.5833
            cont: 3.1
        bounds:
            HH: [ 2.4, 2.45 ]
            LH: [ 2.4, 2.7 ]
            cont: [ 3.05, 3.3 ]

    abs_shift:
        unit: 'eV'
        p0: 0.0
        bounds: [ 0.0, 0.015 ]

fit_vars_model_biexc:
    fse:
        unit: ''
        p0: 0.01
        bounds: [ 0.0, 1.0 ]

    fdepl:
        unit: ''
        p0: 0.01
        bounds: [ 0.0, 1.0 ]

    alpha:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]

    pump_mu:
        unit: 'eV'
        p0:
            HH: 2.4188
            LH: 2.5833
            cont: 3.1
        bounds:
            HH: [ 2.4, 2.45 ]
            LH: [ 2.58, 2.7 ]
            cont: [ 3.05, 3.3 ]

    abs_shift:
        unit: 'eV'
        p0: 0.0
        bounds: [ 0.0, 0.015 ]

    hhhh_mag:
        unit: ''
        p0: 0.002
        bounds: [ 0.0, 0.004 ]

    hhlh_mag:
        unit: ''
        p0: 0.002
        bounds: [ 0.0, 0.004 ]

    hhhh_loc:
        unit: 'eV'
        p0: 2.38
        bounds: [ 2.33, 2.4 ]

    hhlh_loc:
        unit: 'eV'
        p0: 2.5
        bounds: [ 2.45, 2.55 ]

    hhhh_sig:
        unit: 'eV'
        p0: 0.01
        bounds: [ 0.005, 0.02 ]

    hhlh_sig:
        unit: 'eV'
        p0: 0.01
        bounds: [ 0.005, 0.02 ]

alpha_fit:
    tau0:
        unit: 'ps'
        p0: 0.1
        bounds: [ 0.0, inf ]
    tau1:
        unit: 'ps'
        p0: 10.0
        bounds: [ 0.0, inf ]
    tau2:
        unit: 'ps'
        p0: 10.0
        bounds: [ 0.0, inf ]

    t0:
        unit: 'ps'
        p0: 0.1
        bounds: [ 0.0, inf ]
    t1:
        unit: 'ps'
        p0: 1.0
        bounds: [ 0.0, inf ]
    t2:
        unit: 'ps'
        p0: 10.0
        bounds: [ 0.0, inf ]

    v0:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]
    v1:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]
    v2:
        unit: ''
        p0: 0.1
        bounds: [ 0.0, 1.0 ]


alpha_fit_v2:
    tau0:
        unit: 'ps'
        p0: 0.1
        bounds: [ 0.0, inf ]
    tau1:
        unit: 'ps'
        p0: 10.0
        bounds: [ 0.0, inf ]
    tau2:
        unit: 'ps'
        p0: 100.0
        bounds: [ 0.0, inf ]

    v0:
        unit: 'ps'
        p0: 0.1
        bounds: [ 0.0, inf ]
    v1:
        unit: 'ps'
        p0: 10.0
        bounds: [ 0.0, inf ]
    v2:
        unit: 'ps'
        p0: 100.0
        bounds: [ 0.0, inf ]

